# Docker and Docker Compose based environment for Drupal.
# See https://github.com/blinkreaction/docker-fig-drupal for more information and documentation.

version: "2"

services:
  # Web node
  web:
    build: .
    environment:
      - PORT=10099
    hostname: local.nba.com
    ports:
      - "3099:3099"

networks:
  default:

